### PR TITLE
Update class.MyBBIntegrator.php

### PR DESCRIPTION
**Pull request by virre131**
chanced uid to id, it's in id in new versions of MyBB

### CODE REVIEW

**Comment by isaacrg** [comment]
@olada ?

**Comment by olada** [comment]
Sorry - my bad.
Merged finally.

**Comment by isaacrg** [comment]
@olada Thanks for merging it! I previously had to use the fork.

**Comment by Sama34** [comment]
@olada If I'm not wrong the query should now check for `isgroup` value to be `0`. Otherwise you may end up deleting groups.
```PHP
$this->db->delete_query("moderators", "id='{$user_id}' AND isgroup='0'");
```

**Pull request merged**
